name: Patch and Build

on:
  push:
    branches: [ "**" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Configure Git User Details
        run: git config --global user.email "actions@github.com" && git config --global user.name "Github Actions"
      - name: Apply Patches
        run: ./gradlew applyPatches
      - name: Build
        run: ./gradlew createReobfBundlerJar createReobfPaperclipJar
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Folia Artifacts
          path: ./build/libs/*.jar
      - name: Publish Release
        uses: softprops/action-gh-release@v1
        with:
          files: "build/libs/*.jar"
          body: |
            Commit ${{ steps.short_sha.outputs.sha_short }}
            This release is automatically compiled by GitHub Actions
          name: Folia Automation Compile ${{ steps.short_sha.outputs.sha_short }}
          draft: false
          tag_name: commit-${{ steps.short_sha.outputs.sha_short }}
          generate_release_notes: true
